// Generated by Selenium IDE
const { Builder, By, Key, until, Capabilities} = require('selenium-webdriver')
const chrome = require('selenium-webdriver/chrome');
const assert = require('assert')
const path = require("chromedriver")

describe('Default Suite', function() {
  this.timeout(30000)
  let driver
  let vars
  let chromeCapabilities = Capabilities.chrome()
  var chromeOptions = {'excludeSwitches': ['enable-automation']};
  chromeCapabilities.set('chromeOptions', chromeOptions);
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').withCapabilities(chromeCapabilities).build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('logout', async function() {
    await driver.get("https://zethedeveloper.github.io/Movie-Streaming-Website/home.html")
    await driver.manage().window().maximize()
    await driver.findElement(By.css(".btn-light")).click()
  })
  it('signInTest', async function() {
    await driver.get("https://zethedeveloper.github.io/Movie-Streaming-Website/")
    await driver.manage().window().maximize()
    await driver.findElement(By.linkText("Register")).click()
    await driver.findElement(By.name("email")).sendKeys("kxt@gmail.com")
    await driver.findElement(By.id("pass_signup")).click()
    await driver.findElement(By.id("pass_signup")).sendKeys("abc123!@#ABC")
    await driver.findElement(By.id("pass_signup")).sendKeys(Key.ENTER)
  })
  it('navigationTest', async function() {
    await driver.get("https://qazimaazarshad.github.io/Movie-Streaming-Website/home.html")
    await driver.manage().window().maximize()
    await driver.findElement(By.linkText("Movies")).click()
    await driver.findElement(By.linkText("Web Series")).click()
    await driver.findElement(By.linkText("Kids")).click()
    await driver.findElement(By.linkText("TV")).click()
    await driver.findElement(By.linkText("Premium")).click()
    await driver.findElement(By.linkText("Contact Us")).click()
  })
})
