name: CI for Movie Streaming 

on: [push, pull_request] #during push events

jobs:
  build:
    runs-on: ubuntu-latest # build on ubuntu latest, ubuntu kernel good enough for building different development project, therefore always used as base OS
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Run Code Climate
      uses: erzz/codeclimate-standalone@v0.0.4
      with:
        info_threshold: 10
        minor_threshold: 5
        major_threshold: 1
        critical_threshold: 0
        blocker_threshold: 0
        
    - name: HTML5Validator
      uses: Cyb3r-Jak3/html5validator-action@v7.1.1
      with:
        root: ./html5validator/tests/multiple_ignores/
        blacklist: invalid
        css: true
        
    - uses: actions/upload-artifact@v3
      with:
        name: log
        path: log.log


    
        
        
